// This is where we insert all the contact info in the pop up

function displayContactInfo() {
    document.getElementById("contact-info-overlay").style.display = 'block';

    document.getElementById("contact-text").innerHTML = "<p><em>English Follows</em></p><p>AVIS DE STATUT BÊTA <br>L'application CAMMM Atlas est actuellement en cours de développement et est encore en statut Bêta. Vous pouvez envoyer vos commentaires et rapports de crash aux adresses e-mail suivantes ainsi que les problèmes techniques : <a href=\"mailto:firdous.nizar@umontreal.ca,omar.ortizmeraz@mail.concordia.ca\">firdous.nizar@umontreal.ca</a> et  <a href=\"mailto:firdous.nizar@umontreal.ca,omar.ortizmeraz@mail.concordia.ca\">omar.ortizmeraz@mail.concordia.ca</a>.</p><p>Informations de contact <br>Pour tout ce qui concerne les demandes pour les médias web/imprimés, les demandes de collaboration, les questions de développement, l'ajout de nouvelles données ou la mise à jour d'informations, veuillez nous contacter aux adresses e-mail suivantes :<a href=\"mailto:carmela.cucuzzella@umontreal.ca,firdous.nizar@umontreal.ca,omar.ortizmeraz@mail.concordia.ca\">carmela.cucuzzella@umontreal.ca</a>, <a href=\"mailto:carmela.cucuzzella@umontreal.ca,firdous.nizar@umontreal.ca,omar.ortizmeraz@mail.concordia.ca\">firdous.nizar@umontreal.ca</a>, et  <a href=\"mailto:carmela.cucuzzella@umontreal.ca,firdous.nizar@umontreal.ca,omar.ortizmeraz@mail.concordia.ca\">omar.ortizmeraz@mail.concordia.ca</a>.</p>"
        + "<p>BETA STATUS DISCLAIMER <br>The CAMMM Atlas application is currently under development and is still in Beta status. You can send your feedback, crash reports to the following email addresses and technical issues: <a href=\"mailto:firdous.nizar@umontreal.ca,omar.ortizmeraz@mail.concordia.ca\">firdous.nizar@umontreal.ca</a> and <a href=\"mailto:firdous.nizar@umontreal.ca,omar.ortizmeraz@mail.concordia.ca\">omar.ortizmeraz@mail.concordia.ca</a>.</p><p>Contact information <br>Everything related to inquiries for web/printed media, requests for collaborations, development queries, adding new data or updating information, please contact us in the following emails: <a href=\"mailto:carmela.cucuzzella@umontreal.ca,firdous.nizar@umontreal.ca,omar.ortizmeraz@mail.concordia.ca\">carmela.cucuzzella@umontreal.ca</a>, <a href=\"mailto:carmela.cucuzzella@umontreal.ca,firdous.nizar@umontreal.ca,omar.ortizmeraz@mail.concordia.ca\">firdous.nizar@umontreal.ca</a>, and <a href=\"mailto:carmela.cucuzzella@umontreal.ca,firdous.nizar@umontreal.ca,omar.ortizmeraz@mail.concordia.ca\">omar.ortizmeraz@mail.concordia.ca</a>.</p>";
}

function closeContactInfo() {
    document.getElementById("contact-info-overlay").style.display = 'none';
}